package org.modellwerkstatt.libu.LiefKond.core.ui;

/*Generated by MPS */

import org.modellwerkstatt.objectflow.runtime.IOFXPlatform;
import org.modellwerkstatt.objectflow.runtime.IOFXSession;

public class Ressource_RICH implements IOFXPlatform {
  private String platformName = "RICH";

  public Ressource_RICH() {
  }
  public boolean isPlatform(String platform, IOFXSession __manMapSession) {
    return platformName.equals(platform);
  }
  public void setPlatformName(String pf) {
    platformName = pf;
  }
  public String getPlatformName() {
    return platformName;
  }
  public String getTextForLabel(String labelSpecName) {

    throw new RuntimeException("This can not be true. No text for label '" + labelSpecName + "' found.");
  }

  public String getIconForLabel(String iconSpecName) {

    throw new RuntimeException("This can not be true. No icon for label '" + iconSpecName + "' found.");
  }

  public String getHotKeyForLabel(String hotkeySpecName) {

    throw new RuntimeException("This can not be true. No hotkey for '" + hotkeySpecName + "' found.");
  }

  public boolean isHideOnDisabledForLabel(String isHideSpecName) {

    throw new RuntimeException("This can not be true. No hide spec for '" + isHideSpecName + "' found.");
  }
}
