package org.modellwerkstatt.libu.LiefKond.vereinbarung.ui;

/*Generated by MPS */

import org.modellwerkstatt.dataux.runtime.dsl.ui.PagePane;
import org.modellwerkstatt.dataux.runtime.dsl.ui.GridLayout;
import org.modellwerkstatt.dataux.runtime.dsl.ui.DelegateForm;
import org.modellwerkstatt.dataux.runtime.dsl.ui.F;
import org.modellwerkstatt.dataux.runtime.extensions.IDlgt;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Kondition_Zyklus;
import org.modellwerkstatt.dataux.runtime.dsl.ui.Table;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.GueltigekonditionInfo;
import org.modellwerkstatt.dataux.runtime.dsl.ui.T;
import org.modellwerkstatt.dataux.runtime.dsl.menu.Menu;
import org.modellwerkstatt.objectflow.runtime.SelectionProvider;
import org.modellwerkstatt.objectflow.runtime.CmdParams;

public class KonditionsuebersichtPP implements PagePane.PagePaneDescription<KonditionsuebersichtSuche> {

  public void build(PagePane<KonditionsuebersichtSuche> pagePane) {

    pagePane.bindTo(KonditionsuebersichtSuche.class);
    pagePane.needsFullSizeWindow();

    {
      GridLayout grid10 = pagePane.createGridLayout();
      grid10.columnWeights(GridLayout.Weight.ONE);
      grid10.rowWeights(GridLayout.Weight.MINIMAL, GridLayout.Weight.MINIMAL, GridLayout.Weight.ONE);

      {
        DelegateForm<KonditionsuebersichtSuche> formKonditionsuebersichtSuche_20 = pagePane.createDelegateForm(KonditionsuebersichtSuche.class);
        formKonditionsuebersichtSuche_20.columnWeights(DelegateForm.Weight.ONE);
        formKonditionsuebersichtSuche_20.bindTo(KonditionsuebersichtSuche.class, "");

        formKonditionsuebersichtSuche_20.addIntegerDelegate(F.property("lieferantNr").label("LieferantNr").option(IDlgt.Opt.ISSUE_UPDATE_CONCLUSION));
        formKonditionsuebersichtSuche_20.addStringDelegate(F.property("lieferantName").label("LieferantName").option(IDlgt.Opt.FORCE_DISABLED));
        formKonditionsuebersichtSuche_20.addLocalDateDelegate(F.property("stichtag").label("Stichtag").option(IDlgt.Opt.ISSUE_UPDATE_CONCLUSION));
        formKonditionsuebersichtSuche_20.addIntegerDelegate(F.property("wgHauptNr").label("WgHauptNr").option(IDlgt.Opt.ISSUE_UPDATE_CONCLUSION));
        formKonditionsuebersichtSuche_20.addIntegerDelegate(F.property("wgUnterNr").label("WgUnterNr").option(IDlgt.Opt.ISSUE_UPDATE_CONCLUSION));
        formKonditionsuebersichtSuche_20.addStatusDelegate(F.property("zyklus").label("Zyklus").option(IDlgt.Opt.ISSUE_UPDATE_CONCLUSION).optionalText(Kondition_Zyklus.OPTIONAL_TEXT));
        grid10.insert(formKonditionsuebersichtSuche_20);
      }
      {
        DelegateForm<KonditionsuebersichtSuche> formKonditionsuebersichtSuche_21 = pagePane.createDelegateForm(KonditionsuebersichtSuche.class);
        formKonditionsuebersichtSuche_21.formEditingDisabled();
        formKonditionsuebersichtSuche_21.columnWeights(DelegateForm.Weight.ONE);
        formKonditionsuebersichtSuche_21.bindTo(KonditionsuebersichtSuche.class, "");

        formKonditionsuebersichtSuche_21.addStringDelegate(F.property("hinweis").label("Hinweis").numLines(4));
        grid10.insert(formKonditionsuebersichtSuche_21);
      }
      {
        Table<GueltigekonditionInfo> tableGueltigekonditionInfo_22 = pagePane.createTable(GueltigekonditionInfo.class);

        tableGueltigekonditionInfo_22.titleText("GueltigekonditionInfo");
        tableGueltigekonditionInfo_22.addDelegate(T.property("lieferantName").percentWidth(12).label("LieferantName"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("vereinbarungBezeichnung").percentWidth(12).label("VereinbarungBezeichnung"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("bezeichnung").percentWidth(10).label("Bezeichnung"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("berechnungsart").percentWidth(8).label("Berechnungsart"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("satzText").percentWidth(6).label("SatzText"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("zyklus").percentWidth(6).label("Zyklus"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("warengruppeText").percentWidth(10).label("WarengruppeText"));
        tableGueltigekonditionInfo_22.addDateTimeDateOnlyDelegate(T.property("gueltigVon").percentWidth(6).label("GueltigVon"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("wirksamBisText").percentWidth(12).label("WirksamBisText"));
        tableGueltigekonditionInfo_22.addDelegate(T.property("istVerwendet").percentWidth(6).label("IstVerwendet"));

        tableGueltigekonditionInfo_22.bindTo(KonditionsuebersichtSuche.class, "results");
        tableGueltigekonditionInfo_22.addMenu(Menu.of(Menu.subMenu("", Menu.cmd("org.modellwerkstatt.libu.LiefKond.vereinbarung.ui.VereinbarungOeffnen", (SelectionProvider selection) -> {
          GueltigekonditionInfo gueltigekonditionInfo = selection.of(GueltigekonditionInfo.class);

          if (CmdParams.notAvailable(gueltigekonditionInfo)) {
            return null;
          }
          return CmdParams.of(gueltigekonditionInfo.getVereinbarungId());
        }))));
        grid10.insert(tableGueltigekonditionInfo_22);
      }
      pagePane.insert(grid10);
    }

  }
}
