package org.modellwerkstatt.libu.LiefKond.vereinbarung.ui;

/*Generated by MPS */

import org.modellwerkstatt.dataux.runtime.dsl.ui.PagePane;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Kondition;
import org.modellwerkstatt.dataux.runtime.dsl.ui.DelegateForm;
import org.modellwerkstatt.dataux.runtime.dsl.ui.F;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Kondition_Berechnungsart;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Kondition_Zyklus;

public class KonditionPP implements PagePane.PagePaneDescription<Kondition> {

  public void build(PagePane<Kondition> pagePane) {

    pagePane.bindTo(Kondition.class);

    {
      DelegateForm<Kondition> formKondition_10 = pagePane.createDelegateForm(Kondition.class);
      formKondition_10.formEditingDisabled();
      formKondition_10.columnWeights(DelegateForm.Weight.ONE);
      formKondition_10.bindTo(Kondition.class, "");

      formKondition_10.addStringDelegate(F.property("vereinbarung.lieferantName").label("Vereinbarung-LieferanenBez"));
      formKondition_10.addStringDelegate(F.property("vereinbarung.bezeichnung").label("Vereinbarung-Bezeichnung"));
      formKondition_10.addStringDelegate(F.property("bezeichnung").label("Bezeichnung"));
      formKondition_10.addStatusDelegate(F.property("berechnungsart").label("Berechnungsart").optionalText(Kondition_Berechnungsart.OPTIONAL_TEXT));
      formKondition_10.addDecimalDelegate(F.property("satzProzent").label("SatzProzent"));
      formKondition_10.addDecimalDelegate(F.property("betragJeEinheit").label("BetragJeEinheit"));
      formKondition_10.addStringDelegate(F.property("einheit").label("Einheit"));
      formKondition_10.addStatusDelegate(F.property("zyklus").label("Zyklus").optionalText(Kondition_Zyklus.OPTIONAL_TEXT));
      formKondition_10.addStringDelegate(F.property("warengruppeName").label("WarengruppeName"));
      formKondition_10.addLocalDateDelegate(F.property("gueltigVon").label("GueltigVon"));
      formKondition_10.addLocalDateDelegate(F.property("gueltigBis").label("GueltigBis"));
      formKondition_10.addDateTimeDelegate(F.property("audit.erstelltAm").label("ErstelltAm"));
      formKondition_10.addStringDelegate(F.property("audit.erstelltVon").label("ErstelltVon"));
      formKondition_10.addDateTimeDelegate(F.property("audit.geaendertAm").label("GeaendertAm"));
      formKondition_10.addStringDelegate(F.property("audit.geaendertVon").label("GeaendertVon"));
      pagePane.insert(formKondition_10);
    }

  }
}
