package org.modellwerkstatt.libu.LiefKond.vereinbarung.ui;

/*Generated by MPS */

import org.modellwerkstatt.objectflow.runtime.OFXCommand;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Kondition;
import org.springframework.beans.factory.annotation.Autowired;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.KonditionS;
import org.modellwerkstatt.libu.LiefKond.core.domain.Roles;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.KonditionR;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.KonditionAnzeigeS;
import org.modellwerkstatt.objectflow.runtime.IOFXPlatform;
import org.modellwerkstatt.objectflow.runtime.IOFXTranslationProvider;
import org.modellwerkstatt.objectflow.runtime.IOFXCommand;
import org.modellwerkstatt.objectflow.runtime.IOFXSession;
import org.modellwerkstatt.objectflow.runtime.OFXCommandPage;
import org.modellwerkstatt.objectflow.runtime.OFXCommandPageConclusion;
import org.modellwerkstatt.objectflow.runtime.OFXChangePageException;
import org.modellwerkstatt.objectflow.runtime.OFXCommandDoneException;
import org.modellwerkstatt.objectflow.runtime.OFXAbortedException;
import org.modellwerkstatt.objectflow.runtime.IOFXSessionOperation;
import java.util.List;
import org.modellwerkstatt.objectflow.runtime.IOFXProblem;
import java.util.ArrayList;
import org.modellwerkstatt.objectflow.runtime.OFXSuccessorCommandConfig;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class Kondition__ffnen extends OFXCommand {

  private int konditionId;
  private Kondition kondition;

  @Autowired
  private KonditionS __domainKonditionS;
  @Autowired
  private Roles __domainRoles;
  @Autowired
  private KonditionR __domainKonditionR;
  @Autowired
  private KonditionAnzeigeS __domainKonditionAnzeigeS;
  @Autowired
  private IOFXPlatform __runtimeIOFXPlatform;
  @Autowired
  private IOFXTranslationProvider __runtimeIOFXTranslationProvider;

  public Kondition__ffnen() {
    super("org.modellwerkstatt.libu.LiefKond.vereinbarung.ui.Kondition__ffnen", "Kondition öffnen", null, IOFXCommand.OFXWindowTitleType.OVERWRITE, false, false, 1);

    cmdOptions = new IOFXCommand.OFXCmdOptions[]{};
  }
  public void setCommandParams(IOFXSession __manMapSession, Object[] args) {
    konditionId = (Integer) args[0];

    page(new OFXCommandPage<Kondition>("Kondition", 1) {
      public void initGenPageConclusion() {
        conclusion(new OFXCommandPageConclusion("Speichern", true) {
          public boolean isEnabled() {
            if (Kondition__ffnen.this.isCurrentlyReadOnlySession()) {
              return false;
            }
            return true;
          }
          public void execute() throws OFXChangePageException, OFXCommandDoneException, OFXAbortedException, Exception {
            __domainKonditionS.pruefeKondition(kondition, 0, __manMapSession);
            throw new OFXCommandDoneException("done");
          }
        });
      }
      public Object pageLoadFunction() throws Exception {
        return kondition;
      }
      public void calcScopes() {
      }
      public String calcPagePaneFqName() {
        return "org.modellwerkstatt.libu.LiefKond.vereinbarung.ui.KonditionPP";
      }

    });
    super.setCommandParams(__manMapSession, false);
  }
  public void initCommandStatements() throws Exception {
    kondition = __domainKonditionR.checkoutKondition(konditionId, __manMapSession);
    __domainKonditionAnzeigeS.ergaenzeAnzeige(kondition, __manMapSession);

  }
  @Override
  public String getWindowTitle() {
    cmdTitleAddOn = __runtimeIOFXTranslationProvider.translate(__manMapSession.getUserEnvironment().getLangIndex(), "Kond %d", konditionId);
    return cmdTitleAddOn;
  }
  public void finalOkStatements() {
    __manMapSession.addOperation(new IOFXSessionOperation() {
      public void execute() {
        __domainKonditionR.checkInKondition(kondition, __manMapSession);
      }
      public String getInformation() {
        return "Operation call to KonditionR.checkInKondition() in Kondition öffnen";
      }
    });
  }
  public void finalCancelStatementsAndMarker(List<IOFXProblem> listOfProblems) throws Exception {
  }
  public List<String> getLockNecessaryLockNames() {
    List<String> locks = new ArrayList<String>();
    return locks;
  }

  public OFXSuccessorCommandConfig getSuccessorCommandConfig() {
    return null;
  }

  public List<Object> getTerminateCancelSelections() {
    return ListSequence.fromList(new ArrayList<Object>());
  }
  public List<Object> getTerminateOkSelections() {
    return ListSequence.fromListAndArray(new ArrayList<Object>(), kondition);
  }
  public Object getTerminateOkObjectForId(String name) {
    throw new RuntimeException("The id '" + name + "' is not defined as create information key?");
  }
  public void startShadowing() {
  }
  public void clearShadowing() {
  }
  public void revertToShadow() {
  }
}
