package org.modellwerkstatt.libu.LiefKond.vereinbarung.ui;

/*Generated by MPS */

import org.modellwerkstatt.dataux.runtime.dsl.ui.PagePane;
import org.modellwerkstatt.libu.LiefKond.vereinbarung.domain.Vereinbarung;
import org.modellwerkstatt.dataux.runtime.dsl.ui.DelegateForm;
import org.modellwerkstatt.dataux.runtime.dsl.ui.F;

public class VereinbarungLoeschenPP implements PagePane.PagePaneDescription<Vereinbarung> {

  public void build(PagePane<Vereinbarung> pagePane) {

    pagePane.bindTo(Vereinbarung.class);

    {
      DelegateForm<Vereinbarung> formVereinbarung_10 = pagePane.createDelegateForm(Vereinbarung.class);
      formVereinbarung_10.formEditingDisabled();
      formVereinbarung_10.columnWeights(DelegateForm.Weight.ONE);
      formVereinbarung_10.bindTo(Vereinbarung.class, "");

      formVereinbarung_10.addIntegerDelegate(F.property("lieferantNr").label("LieferantNr"));
      formVereinbarung_10.addStringDelegate(F.property("lieferantName").label("LieferanenBez"));
      formVereinbarung_10.addStringDelegate(F.property("bezeichnung").label("Bezeichnung"));
      formVereinbarung_10.addStringDelegate(F.property("externeReferenz").label("ExterneReferenz"));
      formVereinbarung_10.addLocalDateDelegate(F.property("gueltigVon").label("GueltigVon"));
      formVereinbarung_10.addLocalDateDelegate(F.property("gueltigBis").label("GueltigBis"));
      pagePane.insert(formVereinbarung_10);
    }

  }
}
